import Head from "next/head";
import { Box, VStack, Heading, Text, SimpleGrid } from "@chakra-ui/react";
import CardAlbum from "../components/CardAlbum";

export default function Home(props) {
  const { users } = props;
  return (
    <>
      <Head>
        <title>Gallery Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box my={4}>
        <VStack align="start" spacing="-px">
          <Heading size="xl" fontFamily="sans-serif">
            Albums
          </Heading>
          <Text fontSize="xs" color="GrayText" fontFamily="mono">
            {users.length} albums
          </Text>
        </VStack>
        <SimpleGrid mt={4} columns={{ base: 2, sm: 3 }} spacing={4}>
          {users.map((item) => (
            <CardAlbum
              key={item.albums.id}
              albumId={item.albums.id}
              amount={item.albums.id}
              nameAlbum={item.albums.title.toUpperCase()}
              username={item.username}
            />
          ))}
        </SimpleGrid>
      </Box>
    </>
  );
}

export async function getStaticProps(context) {
  let res = [];
  await fetch("https://jsonplaceholder.typicode.com/albums")
    .then((response) => response.json())
    .then((data) => {
      return Promise.all(
        data.map(async (item) => {
          const response = await fetch(
            "https://jsonplaceholder.typicode.com/users/" + item.userId
          );
          const data = await response.json();
          return {
            ...data,
            albums: item,
          };
        })
      );
    })
    .then((data) => (res = data));

  return {
    props: {
      users: res,
    }, // will be passed to the page component as props
  };
}
